### PR TITLE
\expanded primitive

### PR DESCRIPTION
**Pull request by h-kitagawa**
Joseph Wright さんのメール（ http://tug.org/pipermail/tex-live/2018-May/041599.html ）参照．彼は expnaded.ch という小さい change file を新規に作っていましたが，私は pdfutils.ch に統合したほうが保守が楽になると思っています．ChangeLog は未整備．

### CODE REVIEW

**Comment by josephwright** [comment]
Based on discussion on the pdfTeX list, this primitive will be added there: I'd be very appreciative if the same could happen in (u)pTeX.

**Comment by aminophen** [comment]
Thanks. I'll commit this change to TeX Live svn tonight after testing. Would you like to bump version number \epTeXversion 20180518 for this primitive addition? > @h-kitagawa

**Comment by h-kitagawa** [comment]
> Would you like to bump version number \epTeXversion 20180518 for this primitive addition? > @h-kitagawa

Updated to 180518.

**Comment by aminophen** [comment]
Done (r47745).

**Pull request merged**
